sudo: false
language: go
go:
- 1.5.4
- 1.6.2
before_install:
- bash scripts/gitcookie.sh
- go get github.com/smartystreets/goconvey/convey
- if [ ! -d $SNAP_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/intelsdi-x; ln -s $TRAVIS_BUILD_DIR $SNAP_SOURCE; fi # CI for forks not from intelsdi-x
env:
  global:
    - SNAP_SOURCE=/home/travis/gopath/src/github.com/intelsdi-x/snap
    - GO15VENDOREXPERIMENT=1
  matrix:
    - SNAP_TEST_TYPE=legacy
    - SNAP_TEST_TYPE=small
install:
- export TMPDIR=$HOME/tmp
- mkdir -p $TMPDIR
- cd $SNAP_SOURCE # change dir into source
- make
script:
- make check 2>&1 # Run test suite
notifications:
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
